version: '3'
services:
  santa-app:
    build: .
    working_dir: /bot/
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - santa_network
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - santa_network
networks:
  santa_network:
    driver: bridge
